version: '3.7'

services:
  coma-front-dev:
    container_name: coma-front-dev_cont
    image: coma-front:dev
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
    ports:
      - "5000:5000"
    networks: 
      - coma
  coma-front-prod:
    container_name: coma-front-prod_cont
    image: coma-front:prod
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks: 
      - coma
networks: 
  coma:
